# PATHS
train_dataset: ./data/train_valid
validation_dataset: ./data/test_valid
predict_dataset: ./data/test_valid
additional_functions_file: ./additional_functions.py
output_path: ./
load_model_path: ./CheckPoint/experiment_2024_09_30_06_54_35/ckpt/weights.49-0.111

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
metrics: [MeanAbsolutePercentageError, MeanAbsoluteError, MeanSquaredError, RootMeanSquaredError, MeanSquaredLogarithmicError]

# TRAINING OPTIONS
batch_size: 128
epochs: 50
epoch_size: 1690
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 1690 
val_frequency: 1
#initial_epoch: 35
