# PATHS
train_dataset: ../4tier/data-reduced/train_valid
validation_dataset: ../4tier/data-reduced/validation_valid
#validation_dataset: ../social-network/data-mili/validation_valid
#predict_dataset: ./data/test
additional_functions_file: ./additional_functions.py
output_path: ./
#load_model_path: ./CheckPoint/experiment_2024_04_22_11_16_42/ckpt/weights.89-0.069/

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
metrics: [MeanAbsolutePercentageError, MeanAbsoluteError, MeanSquaredError, RootMeanSquaredError, MeanSquaredLogarithmicError]

# TRAINING OPTIONS
batch_size: 64
epochs: 50
epoch_size: 1100
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 8934
val_frequency: 1
#initial_epoch: 84
